name: tflite
description: A Flutter plugin for accessing TensorFlow Lite. Supports both iOS and Android.
version: 1.1.2

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  meta: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.16.5
  
flutter:
  plugin:
    platforms:
      android:
        package: sq.flutter.tflite
        pluginClass: TflitePlugin
      ios:
        pluginClass: TflitePlugin